

-- 用户表
CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
	username VARCHAR(64) NOT NULL UNIQUE COMMENT '用户名',
	password_hash VARCHAR(128) NOT NULL COMMENT '密码哈希',
	email VARCHAR(128) COMMENT '邮箱',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);


-- 会话表
CREATE TABLE session (
	id INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT '会话ID',
	user_id INTEGER NOT NULL COMMENT '用户ID',
	token VARCHAR(128) NOT NULL UNIQUE COMMENT '会话令牌',
	expires_at DATETIME NOT NULL COMMENT '过期时间',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);
